---
title: "Argumente für die Beibehaltung des Schwerpunktfachs Wirtschaft und Recht"
---

Mit der Maturitätsanerkennungsverordnung (MAV) vom 1. August 2024 hat
der Bundesrat die Rechtsgrundlagen für die Weiterentwicklung der
gymnasialen Maturität (WEGM) verabschiedet. Darin werden schweizweit
Informatik sowie Wirtschaft & Recht als neue Grundlagenfächer 
festgelegt. Die beiden Fächer ergänzen die bestehenden Grundlagenfächern
wie Mathematik, Deutsch, Biologie etc. Dies bedeutet, dass in Zukunft
alle Schülerinnen und Schüler diese Grundlagenfächer unabhängig vom
gewählten Schwerpunkt besuchen werden. Ebenso gibt der Bund vor, Aspekte
wie z.B. die Interdisziplinarität, die politische Bildung und die
Digitalisierung in Zukunft stärker zu fördern.

Der Kanton Zürich plant als einziger Kanton, die Forderung nach
interdisziplinärem Arbeiten in den Schwerpunktfächern umzusetzen. Weil
der Kanton Zürich Interdisziplinarität als die Zusammenarbeit von zwei
Lehrpersonen mit einer Lehrberechtigung in zwei verschiedenen Fächern
definiert, führt das zur Abschaffung des bestehenden Schwerpunktfachs
Wirtschaft & Recht. Als Ersatz soll ein neues Schwerpunktfach in Kombination
mit einem weiteren Fach geschaffen werden.
Damit
steht der Kanton Zürich der Schweizer
Bildungslandschaft alleine da. Die anderen Kantone setzen auf die bisher
bewährten Schwerpunktfächer und ergänzen allenfalls punktuell den
Katalog der Schwerpunktfächer. Das Schwerpunktfach Wirtschaft & Recht
ist ausserhalb des Kantons Zürich völlig unbestritten.

Im Kanton Zürich muss Wirtschaft & Recht aufgrund des eng gefassten
Verständnisses von Interdisziplinarität mit
einem weiteren Grundlagenfach (z.B. Geografie oder Geschichte) kombiniert werden, damit
die Interdisziplinarität gegeben sei. Die Anzahl Lektionen im Schwerpunktfach Wirtschaft &
Recht soll deshalb um einen substanziellen Anteil (30-50%) reduziert werden, damit Platz für
die verordnete Kombination mit z.B. Geografie oder Geschichte entsteht.

Gemäss offizieller Argumentation sei diese Reduktion zu vernachlässigen,
weil durch das neue Grundlagenfach 
Wirtschaft & Recht zusätzliche Lektionen hinzukommen. Der geplante Wegfall der Lektionen
im Schwerpunkt Wirtschaft & Recht sei dadurch kompensiert.

Diese Aussage ist nachweislich falsch. Zählt man die Lektionen des Grundlagenfaches
W&R und die Lektionen von W&R in den geplanten Schwerpunkten zusammen, kommt es
zu einem substanziellen **Abbau von bis zu einem Drittel** der
heutigen Lektionenzahl in Wirtschaft & Recht.

Gegen diesen Abbau wehren wir uns:

Das Schwerpunktfach Wirtschaft & Recht ist das von den Sek-Schülerinnen und -Schülern
meistgewählte Schwerpunktfach an den Zürcher Gymnasien - und auch schweizweit das
beliebteste Schwerpunktfach.

Der Zürcher Umsetzungsvorschlag ignoriert, dass Wirtschaft & Recht aus
zwei unterschiedlichen Disziplinen besteht: Den
Wirtschaftswissenschaften und den Rechtswissenschaften (und damit
notabene bisher das einzige interdisziplinäre Schwerpunktfach darstellt).

Wirtschaft & Recht ist durch die Kombination von Volkswirtschaftslehre, Betriebswirtschafts-
lehre und Recht bereits seit Jahren ein erfolgreiches, bewährtes und
interdisziplinär ausgerichtetes Schwerpunktfach. Zu beachten ist zudem,
dass die Inhalte des heutigen Fachs 
W&R vor der MAR-Reform 1995 an den Zürcher Gymnasien sogar in drei
verschiedenen Fächern gelehrt wurden. 

**Das aktuelle Schwerpunktfach Wirtschaft & Recht erfüllt somit bereits
heute alle Vorgaben des Bundes in Bezug auf die Interdisziplinarität.**
Die spezifisch Zürcherischen Vorgaben werden nur aufgrund der
überspitzen Anforderungen an die Interdisziplinarität nicht erfüllt.

Eine Kombination mit zusätzlichen Fächern bringt den Schülerinnen und Schülern keinen
Mehrwert, sondern eine klare inhaltliche Verwässerung und verhindert die fachliche Tiefe
in den - insbesondere auch für den Wirtschaftskanton Zürich - sehr
bedeutsamen und zukunftsträchtigen Disziplinen «Wirtschaft» und «Recht». 

Der Schwerpunkt W&R ist bei den Jugendlichen so beliebt, weil

* er sich an ihren Interessen und Bedürfnissen ausrichtet.
* er ihnen einen vertieften Einblick in diese beiden Disziplinen ermöglicht.
* er bereits heute zu grossen Teilen interdisziplinär, anwendungs- und
  praxisorientiert unterrichtet wird.
* er sie befähigt, gesellschaftliche Herausforderungen und Zusammenhänge
  unserer Zeit zu erkennen und zukunftsorientierte Lösungsansätze (mit) zu entwickeln.
* er vielversprechende Studien- und Arbeitsmarktperspektiven bietet.
  
Auch neueste Umfragen unter aktuellen Schülerinnen und Schülern zeigen deutlich, dass sie
keine Verwässerung mit zusätzlichen Fächern wollen.

Fundierte Kompetenzen in wirtschaftlich-rechtlichen Themen unterstützen
das Ziel der vertieften Gesellschaftsreife (Art. 6 Abs. 1 MAR).

Sämtliche anderen Kantone behalten den auch das Schwerpunktfach Wirtschaft & Recht bei. Sie wollen
keine Verwässerung und auch keinen Abbau der Lektionen in Wirtschaft &
Recht. Im Gegenteil, es gibt Kantone, welche die Gesamtzahl der
WR-Lektionen im 
Vergleich zur aktuell gültigen Stundentafel im Kanton Zürich sogar
erhöhen. Als einer von vielen Kantonen kann der 
Kanton St. Gallen erwähnt werden, der neu 18 Jahreslektionen für Wirtschaft & Recht vor-
sieht (4 Jahreslektionen im Grundlagenfach und 14 im Schwerpunktfach).

Verglichen mit dem Ist-Zustand an Zürcher (Wirtschafts-) Gymnasien
würden in Zukunft wirtschaftlich-rechtliche Inhalte im Umfang von rund
einem Jahr Unterricht der Reform zum Opfer fallen. Konkret müssten
mehrere grundlegende, gesellschaftlich und wirtschaftlich höchst 
relevante Themen gänzlich aus dem Lehrplan gestrichen werden. 

Der Kanton Zürich hat über 20 Gymnasien, darunter auch kleine Spezialitätenschulen wie
die Kantonsschulen Hottingen in Zürich und Büelrain in Winterthur. Sie
haben sich traditionsgemäss und erfolgreich auf das Schwerpunktfach
Wirtschaft & Recht fokussiert und bilden 
zwischen 30% bis 40% aller W&R- Gymnasiastinnen und -Gymnasiasten im Kanton Zürich
aus. Durch die Abschaffung des Schwerpunkts W&R und die geplante
Verwässerung verlieren diese Spezialitätenschulen ihre klare
Fokussierung, ihre Attraktivität und dadurch letztlich 
auch ihre eigene Identität.

Der Zürcher Umsetzungsvorschlag nimmt mit der Abschaffung des Schwerpunktfaches
Wirtschaft & Recht bewusst in Kauf, dass etablierte Gymnasien wie Hottingen und Büelrain
ihr Profil und ihre Ausstrahlung verlieren.

Wir fordern deshalb:

* Den Erhalt von Wirtschaft & Recht als eigenständiges, bereits heute
  interdisziplinär ausgerichtetes Schwerpunktfach an den Zürcher
  Gymnasien. 
* Keine unnötige Verwässerung mit anderen Fächern aufgrund einer
  übertrieben formalistischen Definition der Interdisziplinarität.
* Kein Abbau der wirtschaftlich-rechtlichen Bildung durch die Reduktion
  der Anzahl Lektionen in Wirtschaft & Recht und somit auch keine
  Schwächung der wirtschaftlich-rechtlichen Bildung im Wirtschaftskanton
  Zürich. 
* Die Berücksichtigung der Interessen und Bedürfnissen einer Vielzahl
  von Zürcher Schülerinnen und Schüler.
* Den Erhalt von Gymnasien, die sich als kleine Spezialitätenschulen mit
  Ausrichtung Wirtschaft & Recht im Kanton Zürich etabliert und
  profiliert haben. 