---
title: "Ausgangslage"
---

Per 1. August 2024 ist die neue Maturitätsanerkennungsverordnung (MAV)
in Kraft getreten. Die Revision der MAV durch Bund und Kantone erfordert
Anpassungen in der Ausgestaltung der Gymnasien in den Kantonen.

Die Revision der MAV hat dem interdisziplinären Arbeiten einen grösseren
Stellenwert eingeräumt. Mindestens 3% der Unterrichtszeit müssen dafür
aufgewendet werden. Der Kanton Zürich hat sich als einziger Kanton dafür
entschieden, dieses Ziel durch die Ausgestaltung der Schwerpunktfächer
zu erreichen. Ausserdem hat der Kanton Zürich interdisziplinäres
Arbeiten als das Unterrichten durch zwei Lehrpersonen mit einer
Lehrberechtigung in zwei verschiedenen Fächern definiert. Das bedeutet,
dass das bisherige Schwerpunktfach Wirtschaft und Recht in seiner
aktuellen Form nicht mehr angeboten werden darf. Dies obwohl
Wirtschaft und Recht unter der alten MAV das einzige interdisziplinäre
Schwerpunktfach war.  
Anstelle des alten Schwerpunktfachs Wirtschaft und Recht soll neu ein
Fach in Kombination mit Geschichte oder Geographie angeboten werden.
Dadurch gehen gegenüber der aktuellen Situation rund ein Drittel der
Inhalte verloren. Dies betrifft insbesondere betriebswirtschaftliche
Themen und damit das Verständnis für unternehmerische Entscheide.

Für die kleinen Gymnasien Büelrain und Hottingen mit einer
spezialisierten Ausrichtung auf Wirtschaft und Recht bedeutet dies das
die Aufgabe ihrer Identität.

Wir fordern die Beibehaltung des Schwerpunktfachs Wirtschaft und Recht in seiner
aktuellen Form.
